esphome:
  name: airgradient
  platform: ESP8266
  board: d1_mini
  
# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: ""

wifi:
  ssid: ""
  password: ""
  # Enable falback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ""
    password: ""

captive_portal:

i2c:
  sda: D2
  scl: D1
    
image:
  - file: "images/happy.png"
    id: happy
    type: GRAYSCALE
    
  - file: "images/moderate.png"
    id: moderate
    type: GRAYSCALE
  
  - file: "images/miffed.png"
    id: miffed
    type: GRAYSCALE
    
  - file: "images/unhealthy.png"
    id: unhealthy
    type: GRAYSCALE
    
  - file: "images/vunhealthy.png"
    id: vunhealthy
    type: GRAYSCALE
    
  - file: "images/hazardous.png"
    id: hazardous
    type: GRAYSCALE
    
display:
  - platform: ssd1306_i2c
    id: oled
    model: "SSD1306 64x48"
    brightness: 0%

    pages:
      - id: page1
        lambda: |-
          it.image(0, 0, id(happy));
      - id: page2
        lambda: |-
          it.image(0, 0, id(moderate));
      - id: page3
        lambda: |-
          it.image(0, 0, id(miffed));
      - id: page4
        lambda: |-
          it.image(0, 0, id(unhealthy));
      - id: page5
        lambda: |-
          it.image(0, 0, id(vunhealthy));
      - id: page6
        lambda: |-
          it.image(0, 0, id(hazardous));

time:
  - platform: sntp
    id: sntp_time

interval:
  - interval: 5s
    then:  
      display.page.show: !lambda |-
        if (id(pm25).state < 12) {
          return id(page1);
        } else if (id(pm25).state < 35) {
          return id(page2);
        } else if (id(pm25).state < 55) {
          return id(page3);
        } else if (id(pm25).state < 150) {
          return id(page4);
        } else if (id(pm25).state < 250) {
          return id(page5);
        } else {
          return id(page6);
        }

uart:
  - rx_pin: D5
    tx_pin: D6
    baud_rate: 9600
    id: uart1
  - rx_pin: D4
    tx_pin: D3
    baud_rate: 9600
    id: uart2

sensor:
  - platform: sht3xd
    temperature:
      id: temp
      name: "Temperature"
    humidity:
      id: humidity
      name: "Humidity"
    address: 0x44
    update_interval: 5s
  - platform: pmsx003
    type: PMS5003T
    uart_id: uart1
    pm_2_5:
      id: pm25
      name: "Particulate Matter <2.5µm Concentration"
  - platform: senseair
    uart_id: uart2
    co2:
      id: co2
      name: "SenseAir CO2 Value"
    update_interval: 60s
